bot_keywords_USER_AGENTS = [
    "(BOTforJCE)",
    "(bot",
    "-bot",
    ".bot",
    "/bot",
    "/teoma",
    "007ac9",
    "008",
    "192.comagent",
    "200pleasebot",
    "360Spider",
    "360spider",
    "4seohuntbot",
    "50.nu",
    "7Siters",
    "80legs.com/webcrawler",
    ":bot",
    "A6-Indexer",
    "ADMantX",
    "ADmantXPlatform",
    "AHC/2.1",
    "Abonti",
    "Aboundexbot",
    "Acoon",
    "AddThis.com",
    "AdlesseBot",
    "AhrefsBot",
    "Alexa Crawler",
    "Alexa Site Audit",
    "Amazon Route53 Health Check",
    "Amazonaws",
    "Amorank Spider",
    "Analytics SEO Crawler",
    "Antivirus",
    "Apache-HttpClient/5",
    "ApacheBench",
    "Applebot",
    "Arachni",
    "Ask Jeeves",
    "AstuteSRM",
    "Awario",
    "AwarioSmartBot",
    "BLEXBot",
    "BLEXBot Crawler",
    "BTWebClient",
    "BUbiNG",
    "Backlink-Check.de",
    "BacklinkCrawler",
    "Baidu",
    "Baidu Spider",
    "Baiduspider",
    "Barkrowler",
    "BazQux Reader",
    "BazQuxBot",
    "BehloolBot",
    "BingBot",
    "BingPreview",
    "BitlyBot",
    "Blackboard",
    "Blekkobot",
    "Bloglovin",
    "Blogtrottr",
    "BoardReader",
    "BoardReader Blog Indexer",
    "BomboraBot",
    "Bot",
    "Bountii Bot",
    "BrandVerity",
    "Browsershots",
    "Buck",
    "Buck/2.2",
    "Butterfly",
    "Butterfly Robot",
    "Bytespider",
    "CATExplorador",
    "CCBot",
    "CL0NA",
    "CSS Certificate Spider",
    "CareerBot",
    "Castro 2",
    "Catchpoint",
    "Charlotte",
    "Cliqzbot",
    "CloudFlare AMP Fetcher",
    "CloudFlare Always Online",
    "Collectd",
    "CommaFeed",
    "CommonCrawler",
    "CommonCrawlerNode",
    "Cốc Cốc Bot",
    "Datadog Agent",
    "Datanyze",
    "Dataprovider",
    "Daum",
    "Dazoobot",
    "Discobot",
    "DoCoMo/2.0 N905i",
    "Domain Re-Animator Bot",
    "DomainAppender",
    "DomainCrawler",
    "DomainStatsBot",
    "DomainsProject",
    "DotBot",
    "DuckDuckBot",
    "DuckDuckGo",
    "DuckDuckGo Bot",
    "EBAY",
    "EMail Exractor",
    "Easou Spider",
    "EmailWolf",
    "Embedly",
    "ExaBot",
    "Exabot",
    "ExactSeek Crawler",
    "Ezooms",
    "FM Scene",
    "Facebook External Hit",
    "Feed Wrangler",
    "FeedBurner",
    "Feedbin",
    "Feedfetcher",
    "Feedfetcher-Google",
    "Feedly",
    "Feedspot",
    "FemtosearchBot",
    "Fever",
    "Findxbot",
    "Flipboard",
    "FlipboardProxy",
    "Fortiguard",
    "FreshRSS",
    "GarlikCrawler",
    "Generic Bot",
    "Genieo",
    "Genieo Web filter",
    "Gigablast",
    "GigablastOpenSource/1.0",
    "Gigabot",
    "Gluten Free Crawler",
    "GlutenFreeCrawler",
    "Gmail Image Proxy",
    "Go-http-client",
    "Goo",
    "Google",
    "Google Favicon",
    "Google PageSpeed Insights",
    "Google Partner Monitoring",
    "Google Search Console",
    "Google Structured Data Testing Tool",
    "Googlebot",
    "Grapeshot",
    "GrapeshotCrawler",
    "GroupHigh",
    "HTTPMon",
    "HTTP_Request2",
    "Heritrix",
    "Heureka Feed",
    "Http Crawler",
    "HubPages",
    "HubSpot",
    "ICC-Crawler",
    "IDG/IT",
    "IIS Site Analysis",
    "IP-Guide Crawler",
    "IPS Agent",
    "InAGist",
    "Inktomi Slurp",
    "Java/1.8",
    "Jetslide",
    "Kaspersky",
    "KatBot",
    "Kouio",
    "Kraken",
    "LCC",
    "LTX71",
    "Larbin web crawler",
    "Let's Encrypt Validation",
    "Lighthouse",
    "LingueeBot",
    "Linkdex Bot",
    "LinkedIn Bot",
    "LivelapBot",
    "Lycos",
    "MJ12 Bot",
    "MJ12bot",
    "MSNBot",
    "Macintosh",
    "Magpie-Crawler",
    "MagpieRSS",
    "Mail.RU_Bot",
    "Mail.Ru Bot",
    "Mastodon Bot",
    "MaxPointCrawler",
    "Meanpath Bot",
    "Mediapartners-Google",
    "Mediatoolkitbot",
    "MegaIndex",
    "MegaIndex.ru",
    "MetaInspector",
    "MetaJobBot",
    "MetaURI",
    "MicrosoftCorporation",
    "MicrosoftOffice",
    "Mixrank Bot",
    "Mnogosearch",
    "MojeekBot",
    "Monitor.Us",
    "Moreover",
    "Munin",
    "NING",
    "NLCrawler",
    "Nagios check_http",
    "NalezenCzBot",
    "NetLyzer FastProbe",
    "NetNewsWire",
    "NetResearchServer",
    "NetSeercrawler",
    "Netcraft",
    "Netcraft Survey Bot",
    "NetcraftSurveyAgent",
    "Netvibes",
    "NewsBlur",
    "NewsGator",
    "Niki-Bot",
    "Nmap",
    "Nutch",
    "Nutch-based Bot",
    "Nuzzel",
    "Octopus",
    "Omgili bot",
    "OnalyticaBot",
    "OpenLinkProfiler",
    "OpenWebSpider",
    "Openindex Spider",
    "Orange Bot",
    "Outbrain",
    "PHP Server Monitor",
    "PHP-Curl-Class",
    "PagePeeker",
    "PaperLiBot",
    "Pcore-HTTP",
    "PercolateCrawler",
    "PhantomJS",
    "Phantomas",
    "Picsearch bot",
    "Pingdom",
    "Pingdom Bot",
    "Pinterest",
    "PocketParser",
    "Pompos",
    "Prevx",
    "PrintfulBot",
    "PritTorrent",
    "PulseCrawler",
    "Python-urllib",
    "QuerySeekerSpider",
    "Quora Link Preview",
    "Qwantify",
    "R6_CommentReader",
    "R6_FeedFetcher",
    "ROI Hunter",
    "RSSRadio Bot",
    "Rainmeter",
    "Rambler",
    "RamblerMail Image Proxy",
    "Re-AnimatorBot",
    "Reddit Bot",
    "Riddler",
    "Rogerbot",
    "SAMSUNG-SGH-E250",
    "SEOENGBot",
    "SEOkicks",
    "SEOkicks-Robot",
    "SISTRIX Crawler",
    "SISTRIX Optimizer",
    "SISTRIXCrawler",
    "SMTBot",
    "SMXCrawler",
    "SSL Labs",
    "SafeDNSBot",
    "ScooperBot",
    "Scooter",
    "ScoutJet",
    "Scrapy",
    "Screaming Frog SEO Spider",
    "ScreenerBot",
    "SearchmetricsBot",
    "SeekportCrawler",
    "SemanticScholarBot",
    "Semrush Bot",
    "SemrushBot",
    "Sensika Bot",
    "Sentry Bot",
    "Seoscanners.net",
    "SerendeputyBot",
    "Server Density",
    "Seznam Bot",
    "Seznam Email Proxy",
    "Seznam Zbozi.cz",
    "SeznamBot/3.2",
    "ShopAlike",
    "ShopWiki",
    "Shopify Partner",
    "ShowyouBot",
    "SilverReader",
    "SimplePie",
    "Site24x7 Website Monitoring",
    "SiteCheck",
    "SiteLockSpider",
    "SiteSucker",
    "Siteimprove",
    "Sixy.ch",
    "Skype URI Preview",
    "Slackbot",
    "Sleuth",
    "Slurp",
    "Snapchat Proxy",
    "Sogou Spider",
    "Sogouwebspider",
    "Soso Spider",
    "Sparkler",
    "Speedy",
    "Spinn3r",
    "Spotify",
    "Sputnik Bot",
    "Startpagina Linkchecker",
    "StatusCake",
    "StormCrawler",
    "Superfeedr Bot",
    "Survey Bot",
    "TLSProbe",
    "Tarmot Gezgin",
    "TelegramBot",
    "TencentTraveler",
    "The Knowledge AI",
    "TheKnowledgeAI",
    "TinEye Crawler",
    "Tiny Tiny RSS",
    "TinyTinyRSS",
    "Traackr.com",
    "TraceMyFile",
    "Trendiction Bot",
    "TrendsmapResolver",
    "Trident",
    "TurnitinBot",
    "TweetedTimes Bot",
    "TweetedTimesBot",
    "Tweetmeme Bot",
    "TweetmemeBot",
    "Twingly Recon",
    "TwitterFeed",
    "Twitterbot",
    "URLAppendBot",
    "UkrNet Mail Proxy",
    "UniversalFeedParser",
    "UnwindFetchor",
    "Uptime Robot",
    "UptimeRobot",
    "Uptimebot",
    "VK Share Button",
    "Vagabondo",
    "VegeBot",
    "VelenPublicWebCrawler/1.0",
    "Visual Site Mapper Crawler",
    "W3C CSS Validator",
    "W3C I18N Checker",
    "W3C Link Checker",
    "W3C Markup Validation Service",
    "W3C MobileOK Checker",
    "W3C Unified Validator",
    "Wappalyzer",
    "WeSEE:Search",
    "WebPageTest",
    "WebSitePulse",
    "WebThumbnail",
    "WebbCrawler",
    "Weborama",
    "WikiDo",
    "Willow Internet Crawler",
    "WindowsPowerShell",
    "Winds:OpenSourceRSS&Podcast",
    "WooRank",
    "WordPress",
    "WordPress.commShots",
    "Wotbox",
    "XoviBot",
    "Y!J-BRW",
    "YaCy",
    "YaK/1.0",
    "Yahoo Gemini",
    "Yahoo! Cache System",
    "Yahoo! Japan BRW",
    "Yahoo! Link Preview",
    "Yahoo! Slurp",
    "Yahoo!Slurp",
    "Yandex",
    "Yandex Bot",
    "YandexBot",
    "Yeti/Naverbot",
    "YisouSpider",
    "Yottaa Site Monitor",
    "Youdao Bot",
    "YoudaoBot",
    "Yourls",
    "Yunyun Bot",
    "Zao",
    "Ze List",
    "Zombiebot",
    "Zookabot",
    "ZoominfoBot",
    "ZumBotbot",
    "_bot",
    "a6-indexer",
    "aHrefs Bot",
    "abacho",
    "abot",
    "aboundexbot",
    "aboutusbot",
    "above",
    "abrave spider",
    "abravespider",
    "accelobot",
    "accoona",
    "acoi",
    "acoon",
    "acoonbot",
    "acunetix",
    "adaxas",
    "addthis.com",
    "admantx",
    "admantx-adform",
    "adressendeutschland",
    "adsbot",
    "adsbot-google",
    "adscanner",
    "agada",
    "agusescan",
    "ah-ha.com",
    "ahoy",
    "ahrefsbot",
    "aladin",
    "alexabot",
    "alkaline",
    "altavista",
    "amagit.com",
    "amazonaws",
    "amibot",
    "amzn_assoc",
    "amznkassocbot",
    "analytics",
    "ananzi",
    "annotate",
    "anonymizer",
    "antbot",
    "anthill",
    "antivirus",
    "anzwers",
    "anzwerscrawl",
    "apache-httpclient",
    "apercite",
    "aplix",
    "aportworm",
    "app.hypefactors.com",
    "appie",
    "applebot",
    "arabot",
    "arachnophilia",
    "arale",
    "araneo",
    "aranha",
    "architext",
    "archive.org bot",
    "archive.org_bot",
    "aretha",
    "arks",
    "ask24",
    "askaboutoil",
    "asked",
    "aspseek",
    "asterias",
    "atlocal",
    "atn",
    "atomz",
    "augurfind",
    "avant",
    "avast",
    "avg",
    "avira",
    "axios",
    "baboom",
    "backrub",
    "baidu",
    "baiduspider",
    "bannana_bot",
    "baypup",
    "bdfetch",
    "big brother",
    "bigbrother",
    "biglotron",
    "bilbo",
    "bingbot",
    "bingpreview",
    "bitdefender",
    "bitlybot",
    "bjaaland",
    "blackwidow",
    "blaiz",
    "blo.",
    "blog",
    "bloodhound",
    "boitho",
    "booch",
    "bot",
    "bot.",
    "bot/",
    "bradley",
    "butterfly",
    "calif",
    "calyxinstitute",
    "camehttps",
    "cassandra",
    "ccBot crawler",
    "ccubee",
    "cfetch",
    "charlotte",
    "churl",
    "cienciaficcion",
    "cmc",
    "collective",
    "comagent",
    "combine",
    "commoncrawl",
    "compatible",
    "computingsite",
    "crawl",
    "crawlconvera",
    "crawler",
    "cs.daum.net",
    "csci",
    "curl",
    "curl/7",
    "cusco",
    "cyveillance",
    "dalvik",
    "daumoa",
    "dbot",
    "deepindex",
    "del.icio.us",
    "delorie",
    "depspid",
    "deweb",
    "die blinde kuh",
    "dieblindekuh",
    "digger",
    "ditto",
    "dlvr.it",
    "dmoz",
    "docomo",
    "domainappender",
    "download express",
    "downloadexpress",
    "dr.web",
    "dreamhost",
    "dreampassport",
    "drweb",
    "dtaagent",
    "duckduckbot",
    "dwcp",
    "e-collector",
    "eCairn-Grabber",
    "eZ Publish Link Validator",
    "ebay",
    "ebiness",
    "ebingbong",
    "ebot",
    "ejupiter",
    "emacs-w3 search engine",
    "emacs-w3searchengine",
    "esther",
    "evc-batch",
    "evliya celebi",
    "evliyacelebi",
    "exabot",
    "externalhit",
    "ezresult",
    "facebook",
    "facebookexternalhit",
    "falcon",
    "fangcrawl",
    "favicon",
    "feedbot",
    "feedfetcher",
    "felix ide",
    "felixide",
    "ferret",
    "fetchrover",
    "fido",
    "findlinks",
    "fireball",
    "firebird",
    "fish search",
    "fishsearch",
    "fouineur",
    "funnelweb",
    "gazz",
    "gcreep",
    "genieknows",
    "genieo",
    "getstream.io/winds",
    "getterroboplus",
    "geturl",
    "github",
    "glutenfreepleasure.com",
    "glx",
    "go-http-client",
    "go-http-client/1.1",
    "goforit",
    "golem",
    "google",
    "googlebot",
    "googlesafebrowing",
    "googletranslate",
    "grabber",
    "gralon",
    "grapnel",
    "griffon",
    "grokkit-crawler",
    "gromit",
    "grub",
    "gsa-crawler",
    "gulliver",
    "hamahakki",
    "harvest",
    "havindex",
    "hbot",
    "headless",
    "helix",
    "heritrix",
    "hku www octopus",
    "hkuwwwoctopus",
    "homerweb",
    "hotmail",
    "hotmail!",
    "htdig",
    "html index",
    "html_analyzer",
    "htmlgobble",
    "htmlindex",
    "httrack",
    "hubater",
    "hyper-decontextualizer",
    "ia_archiver",
    "ibm_planetwide",
    "ibwww-perl",
    "ichiro",
    "iconsurf",
    "icoreservice",
    "iltrovatore",
    "image.kapsi.net",
    "imagelock",
    "incywincy",
    "indexer",
    "infobee",
    "informant",
    "ingrid",
    "inktomisearch.com",
    "inoreader",
    "insights",
    "inspector web",
    "inspectorweb",
    "instagram",
    "intelliagent",
    "internet shinchakubin",
    "internetshinchakubin",
    "ip3000",
    "ips-agent",
    "iron33",
    "israeli-search",
    "istellabot",
    "ivia",
    "jabber",
    "jack",
    "jakarta",
    "java",
    "javabee",
    "jetbot",
    "jetbrains",
    "jumpstation",
    "kaspersky",
    "katipo",
    "kbot",
    "kdd-explorer",
    "kilroy",
    "knowledge",
    "kototoi",
    "kretrieve",
    "labelgrabber",
    "lachesis",
    "larbin",
    "lbot",
    "legs",
    "libwww",
    "libwww-perl",
    "lighthouse",
    "link validator",
    "linkalarm",
    "linkdex",
    "linkdexbot",
    "linkfluence.com",
    "linkscan",
    "linkvalidator",
    "lockon",
    "lssrocketcrawler",
    "ltx71",
    "lwp",
    "lycos",
    "magpie",
    "magpie-crawler",
    "majestic12",
    "mantraagent",
    "mapoftheinternet",
    "marvin/",
    "masscan",
    "mattie",
    "mbot",
    "mediafox",
    "mediapartners",
    "mediawordsbot",
    "mercator",
    "merlinkbot",
    "merzscope",
    "messagelabs",
    "metadataparser",
    "metauri.com",
    "microsoft url control",
    "microsofturlcontrol",
    "minirank",
    "miva",
    "mj12",
    "mnogosearch",
    "moget",
    "mon.itor.us",
    "monster",
    "moose",
    "motor",
    "msn",
    "msn!",
    "msnbot",
    "msnbot-media",
    "multitext",
    "muncher",
    "muscatferret",
    "mwd.search",
    "myweb",
    "najdi",
    "nameprotect",
    "nationaldirectory",
    "nazilla",
    "nbertaupete95",
    "nbot",
    "ncsa beta",
    "ncsabeta",
    "nec-meshexplorer",
    "nederland.zoek",
    "neofonie",
    "netEstate",
    "netEstateNECrawler",
    "netcarta webmap engine",
    "netcartawebmapengine",
    "netcraft",
    "netmechanic",
    "netpilot",
    "netresearchserver",
    "netscoop",
    "netsparker",
    "newsblur",
    "newscan-online",
    "newspaper",
    "nhse",
    "node",
    "node-fetch",
    "nokia6682/",
    "nomad",
    "noyona",
    "nutch",
    "nzexplorer",
    "oBot",
    "objectssearch",
    "obot",
    "occam",
    "okhttp",
    "okhttp/2.5.0",
    "omgili",
    "omni",
    "open text",
    "openfind",
    "openintelligencedata",
    "opentext",
    "orb search",
    "orbsearch",
    "osis-project",
    "outlook",
    "outlook!",
    "p3pwgdsn",
    "pack rat",
    "packrat",
    "page_verifier",
    "pageboy",
    "pagebull",
    "panscient",
    "parasite",
    "partnersite",
    "patric",
    "paypal",
    "pbot",
    "pear.",
    "pegasus",
    "peregrinator",
    "pgp key agent",
    "pgpkeyagent",
    "phantom",
    "phantomjs",
    "phish",
    "phishtank",
    "phpdig",
    "picosearch",
    "picsearch",
    "piltdownman",
    "pimptrain",
    "pinpoint",
    "pioneer",
    "pipes",
    "piranha",
    "plumtreewebaccessor",
    "pogodak",
    "poirot",
    "pompos",
    "poppelsdorf",
    "poppi",
    "popular iconoclast",
    "populariconoclast",
    "presto",
    "preview",
    "privoxy",
    "profound",
    "proximic",
    "proxy",
    "psycheclone",
    "publisher",
    "pycurl",
    "python",
    "python-requests",
    "quicklook",
    "rambler",
    "raven search",
    "ravensearch",
    "rbot",
    "reverseshorturl",
    "roach",
    "road runner",
    "roadhouse",
    "roadrunner",
    "robbie",
    "robofox",
    "robozilla",
    "rogerbot",
    "rogerbot-crawler",
    "ruby",
    "rules",
    "safebrowsing",
    "safesurfingwidget",
    "salty",
    "samsung-sgh-e250",
    "sbider",
    "sbot",
    "scalaj-http",
    "schmorp.de",
    "scmguard",
    "scooter",
    "scoutjet",
    "scrubby",
    "seamonkey",
    "search.",
    "searchmetrics",
    "searchprocess",
    "seek",
    "semantic-visions.com",
    "semanticdiscovery",
    "semrush.com",
    "senrigan",
    "serpstatbot",
    "sg-scout",
    "shai'hulud",
    "shark",
    "shopwiki",
    "sidewinder",
    "sift",
    "silk",
    "simmany",
    "simplepie",
    "site searcher",
    "site valet",
    "siteexplorer",
    "sitesearcher",
    "sitetech-rover",
    "sitevalet",
    "skymob.com",
    "sleek",
    "slurp",
    "smartwit",
    "sna-",
    "snappy",
    "snooper",
    "softlayer",
    "sogou",
    "sogou-test-spider",
    "sohu",
    "sophos",
    "spam",
    "spbot",
    "speedfind",
    "sphere",
    "sphider",
    "spider",
    "spinn3r",
    "spinner",
    "spyder",
    "sqlmap",
    "steeler/",
    "sucuri.net",
    "suke",
    "suntek",
    "supersnooper",
    "surfnomore",
    "sven",
    "sygol",
    "sylera",
    "sysomos.com",
    "szukacz",
    "t-h-u-n-d-e-r-s-t-o-n-e",
    "t-rex",
    "tach black widow",
    "tachblackwidow",
    "tarantula",
    "tbot",
    "techinfo@ubermetrics-technologies.com",
    "telegram",
    "templeton",
    "terrykyleseoagency.com",
    "theoldreader",
    "theophrastus",
    "titan",
    "titin",
    "tkwww",
    "tor-exit",
    "torservers",
    "toutatis",
    "translate",
    "trendiction",
    "trendictionbot",
    "trendmicro",
    "trident",
    "tutorgig",
    "twiceler",
    "twisted",
    "ubermetrics",
    "ucsd",
    "udmsearch",
    "unchaos",
    "untrusted",
    "updated",
    "updown_tester",
    "url check",
    "urlcheck",
    "urlredirectresolver",
    "urlresolver",
    "vagabondo",
    "valkyrie",
    "vbot",
    "verticrawl",
    "victoria",
    "virus",
    "virustotal",
    "vision-search",
    "volcano",
    "voyager-hc",
    "voyager/",
    "w3c_validator",
    "w3m2",
    "w3mir",
    "walker",
    "wallpaper",
    "wanderer",
    "wapproxy",
    "wauuu",
    "wavefire",
    "web core",
    "web hopper",
    "web wombat",
    "webbandit",
    "webcatcher",
    "webcopy",
    "webcore",
    "webdatastats.com",
    "webfoot",
    "webhopper",
    "weblayers",
    "weblight",
    "weblinker",
    "weblog monitor",
    "weblogmonitor",
    "webmirror",
    "webmonkey",
    "webquest",
    "webreaper",
    "websitepulse",
    "websnarf",
    "webstolperer",
    "webvac",
    "webwalk",
    "webwatch",
    "webwombat",
    "webzinger",
    "wget",
    "whatsapp",
    "whizbang",
    "whowhere",
    "wild ferret",
    "wildferret",
    "windows 95",
    "windows 98",
    "windows95",
    "windows98",
    "woriobot",
    "worldlight",
    "wwwc",
    "wwwster",
    "xenu",
    "xget",
    "xift",
    "xirq",
    "yahoo",
    "yahoo!",
    "yahooSeeker",
    "yandex",
    "yandexbot",
    "yanga",
    "ybot",
    "yeti",
    "yodao",
    "zao/",
    "zbot",
    "zgrab",
    "zipcommander",
    "zippp",
    "zteopen",
    "zyborg",
]
