# Generated by Django 4.2.7 on 2025-10-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="security_answer_1",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="security_answer_2",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="security_answer_3",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="security_question_1",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="security_question_2",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="security_question_3",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
